<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>joseco</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>This library implements the secret request from Hashicorp Vault provider</Description>
    <PackageLicenseFile>README.md</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
    <PackageReference Include="VaultSharp" Version="1.17.5.1" />
    <PackageReference Include="Joseco.Secrets.Contrats" Version="1.0.0" />
  </ItemGroup>

</Project>
